### ISSUE TITLE
ChatBot doesn't work on desktop

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#567] opened 2023-09-21 10:16 UTC
> ChatBot doesn't work, I get an error (Error: Expected event stream content type text/event-stream, got text/html)

From #560

**Comment by cguedes** [comment] 2023-09-21 10:18
We found that this is caused by Tauri's fetch not supporting streaming mode!

Related issue in [Tauri's repo](https://github.com/tauri-apps/tauri/discussions/6613#discussioncomment-5507082).

**Comment by cguedes** [comment] 2023-09-21 10:22
For now we will fallback to use the (non-stream) chat endpoint for the rewrite interaction in desktop.
Later we can test using the fetch api in the desktop code instead of using Tauri's fetch.

**Comment by gjreda** [comment] 2023-09-22 13:55
I think this is fixed now? @cguedes

**Comment by sehyod** [comment] 2023-09-22 13:56
> I think this is fixed now? @cguedes

It has been fixed in https://github.com/refstudio/refstudio/commit/9eb60e57817a82f8c29a2256efb902732762f67a, but the issue is still open because the commit hasn't been merged yet

**Comment by sehyod** [comment] 2023-09-22 13:57
Oh sorry, that was the initial fix, but it has now been fixed by #573 
I think we can close the issue

**Closed** 2023-09-22 13:59 UTC
Labels: bug, app:desktop
